#!/usr/bin/env sh

# Check if a command is available
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if the script is running as root
check_root() {
    [ "$(id -u)" -ne 0 ] || return

    echo "Requires root privileges."
    if command_exists sudo; then
        echo "Enter the user password to continue (sudo):"
        exec sudo "$0" "$@"
    else
        echo "Enter the root user password to continue:"
        exec su -c "$0" "$@"
    fi
}

# Install packages based on the package manager
install_package() {
    for pkg in $1; do
        if command_exists apt; then
            apt install -y --ignore-missing "$pkg"
        elif command_exists apt-get; then
            apt-get install --ignore-missing -y "$pkg"
        elif command_exists yum; then
            yum install -y "$pkg"
        elif command_exists dnf; then
            dnf install -y "$pkg"
        elif command_exists pacman; then
            if [ "$pkg" = "multitail" ]; then
                pacman -S --needed --noconfirm base-devel git
                if command_exists yay; then
                    exec_nosudo="yay -S multitail"
                else
                    exec_nosudo="git clone https://aur.archlinux.org/multitail.git multitail/build/;"
                    exec_nosudo="${exec_nosudo}makepkg -si --noconfirm -D multitail/build/"
                fi
                sudo -u "$SUDO_USER" bash -c "$exec_nosudo"
            else
                pacman -S --noconfirm "$pkg"
            fi
        else
            echo "No known package managers found!"
            exit 1
        fi
    done
}

# Corresponding packages for each command
list_packages() {
    case "$1" in
        bc) echo "bc" ;;
        figlet) echo "figlet" ;;
        htop) echo "htop" ;;
        iostat) echo "sysstat" ;;
        jq) echo "jq" ;;
        multitail) echo "multitail" ;;
        play) echo "sox libsox-fmt-all soxr libsoxr" ;;
        tmux) echo "tmux" ;;
        watch) echo "watch" ;;
        *) echo "" ;;
    esac
}

# List of commands to check
set -- bitcoin-cli tmux htop iostat multitail figlet play jq bc watch

# Check if the commands are installed and install if necessary
for cmd in "$@"; do
    if command_exists "$cmd"; then
        continue
    fi
    echo "The '$cmd' command is not installed."
    packages="$(list_packages "$cmd")"
    if [ -z "$packages" ]; then
        echo "This package will have to be installed manually."
        exit 1
    fi
    echo "Installing..."
    check_root "$@"
    install_package "$packages"
done

exit 0
